name: Publish Xerris.DotNet.Test

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    uses: xerris/xerris-common-workflows/.github/workflows/build-and-publish-to-nuget.yml@main
    with:
      csproj-path: './src/Xerris.DotNet.Test/Xerris.DotNet.Test.csproj'
      nuget-package-name: 'xerris.dotnet.testautomation'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE_URI: ${{ secrets.NUGET_SOURCE_URI }}